"use strict";
const VERSION="7.0";
const STORAGE_KEY="sakaiMoneyPro70";
const LEGACY_KEYS=["sakaiMoneyPro61","sakaiMoneyPro6SecondRelease","sakaiMoneyPro6FirstRelease"];
const $=id=>document.getElementById(id);
const yen=v=>new Intl.NumberFormat("ja-JP",{style:"currency",currency:"JPY",maximumFractionDigits:0}).format(Number(v)||0);
const safeParse=v=>{try{return v?JSON.parse(v):null}catch{return null}};
const clone=v=>JSON.parse(JSON.stringify(v));
const today=()=>new Date().toISOString().slice(0,10);
const currentMonth=()=>new Date().toISOString().slice(0,7);
const uid=()=>`${Date.now()}-${Math.random().toString(16).slice(2)}`;
const escapeHtml=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));

const defaultState={cash:0,loan:0,dark:false,assets:[],plans:[],entries:[],education:[
 {id:"nagi",name:"長女",current:0,target:3000000,color:""},
 {id:"an",name:"次女",current:0,target:3000000,color:""},
 {id:"third",name:"三女",current:0,target:3000000,color:""}
]};
function migrate(){if(localStorage.getItem(STORAGE_KEY))return;for(const k of LEGACY_KEYS){const old=safeParse(localStorage.getItem(k));if(old){localStorage.setItem(STORAGE_KEY,JSON.stringify({...clone(defaultState),...old,loan:Number(old.loan)||0,entries:Array.isArray(old.entries)?old.entries:[],education:Array.isArray(old.education)?old.education:clone(defaultState.education)}));break}}}
migrate();
let state={...clone(defaultState),...(safeParse(localStorage.getItem(STORAGE_KEY))||{})};
state.assets=Array.isArray(state.assets)?state.assets:[];state.plans=Array.isArray(state.plans)?state.plans:[];state.entries=Array.isArray(state.entries)?state.entries:[];state.education=Array.isArray(state.education)&&state.education.length?state.education:clone(defaultState.education);
let currentOwner="本人",editingAssetId=null,editingPlanId=null;
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function assetMetrics(a){const q=Number(a.quantity)||0,c=Number(a.cost)||0,p=Number(a.price)||0;const market=q*p,invested=q*c,profit=market-invested;return{market,invested,profit,rate:invested?profit/invested*100:0}}
function totals(owner=null){return state.assets.filter(a=>!owner||a.owner===owner).reduce((s,a)=>{const m=assetMetrics(a);s.market+=m.market;s.invested+=m.invested;s.profit+=m.profit;s.dividend+=Number(a.dividend)||0;return s},{market:0,invested:0,profit:0,dividend:0})}
function monthEntries(month){return state.entries.filter(e=>(e.date||"").slice(0,7)===month)}
function monthTotals(month){return monthEntries(month).reduce((s,e)=>{s[e.type]+=Number(e.amount)||0;return s},{income:0,expense:0})}
function monthsSince(d){if(!d)return 0;const s=new Date(`${d}T00:00:00`),n=new Date();if(s>n)return 0;return(n.getFullYear()-s.getFullYear())*12+n.getMonth()-s.getMonth()+1}
function renderGreeting(){const h=new Date().getHours();$("greeting").textContent=`${h<11?"おはよう":h<18?"こんにちは":"こんばんは"}、ヒロ`}
function renderTheme(){document.body.classList.toggle("dark",state.dark);$("themeButton").textContent=state.dark?"☀️":"🌙"}
function renderHome(){const all=totals(),mt=monthTotals(currentMonth()),monthly=state.plans.reduce((s,p)=>s+(Number(p.monthly)||0),0),financial=Number(state.cash)+all.market,net=financial-Number(state.loan||0);$("netWorth").textContent=yen(net);$("netWorthSub").textContent=`金融資産 ${yen(financial)} − ローン ${yen(state.loan)}`;$("cashSummary").textContent=yen(state.cash);$("investmentSummary").textContent=yen(all.market);$("monthlyBalance").textContent=yen(mt.income-mt.expense);$("monthlyBalance").className=mt.income-mt.expense<0?"negative":"positive";$("monthlyPlans").textContent=yen(monthly);$("incomeSummary").textContent=yen(mt.income);$("expenseSummary").textContent=yen(mt.expense);$("dividendSummary").textContent=yen(all.dividend);$("profitSummary").textContent=`${all.profit>=0?"+":""}${yen(all.profit)}`;$("profitSummary").className=all.profit<0?"negative":"positive";$("cashInput").value=state.cash||"";$("loanInput").value=state.loan||"";$("educationSummary").innerHTML=state.education.map(e=>{const pct=Math.min(100,e.target?e.current/e.target*100:0);return`<article class="card"><div class="split-row"><span>${escapeHtml(e.name)}</span><strong>${yen(e.current)} / ${yen(e.target)}</strong></div><div class="progress"><span style="width:${pct}%"></span></div></article>`}).join("")}
const cats={income:["給与","ボーナス","配当","児童手当","その他収入"],expense:["食費","日用品","住宅","教育","保険","交通・車","医療","娯楽","投資","その他支出"]};
function renderCategory(){const type=$("entryType").value;$("entryCategory").innerHTML=cats[type].map(c=>`<option>${c}</option>`).join("")}
function renderBudget(){const m=$("budgetMonth").value||currentMonth(),t=monthTotals(m);$("budgetIncome").textContent=yen(t.income);$("budgetExpense").textContent=yen(t.expense);$("budgetBalance").textContent=yen(t.income-t.expense);$("budgetBalance").className=t.income-t.expense<0?"negative":"positive";const list=monthEntries(m).sort((a,b)=>b.date.localeCompare(a.date));$("entryList").innerHTML=list.length?list.map(e=>`<article class="item-card"><div class="item-head"><div><div class="item-title">${escapeHtml(e.memo||e.category)}</div><div class="item-sub">${escapeHtml(e.date)}・${escapeHtml(e.category)}</div></div><div class="item-value ${e.type==='expense'?'negative':'positive'}">${e.type==='expense'?'-':'+'}${yen(e.amount)}</div></div><div class="item-actions"><button class="delete-button" data-delete-entry="${e.id}">削除</button></div></article>`).join(""):`<div class="empty">この月の記録はまだありません。</div>`}
function renderAssets(){const q=$("assetSearch").value.trim().toLowerCase();const list=state.assets.filter(a=>a.owner===currentOwner).filter(a=>!q||a.name.toLowerCase().includes(q)||a.type.toLowerCase().includes(q)).sort((a,b)=>(b.date||"").localeCompare(a.date||""));$("assetList").innerHTML=list.length?list.map(a=>{const m=assetMetrics(a);return`<article class="item-card"><div class="item-head"><div><div class="item-title">${escapeHtml(a.name)}</div><div class="item-sub">${escapeHtml(a.type)}・${escapeHtml(a.account)}・入力日 ${escapeHtml(a.date||"未設定")}</div></div><div class="item-value">${yen(m.market)}<small class="${m.profit<0?'negative':'positive'}">${m.profit>=0?'+':''}${yen(m.profit)}（${m.rate.toFixed(1)}%）</small></div></div><div class="item-grid"><div><span>保有数</span><strong>${Number(a.quantity).toLocaleString("ja-JP")}</strong></div><div><span>取得単価</span><strong>${yen(a.cost)}</strong></div><div><span>現在価格</span><strong>${yen(a.price)}</strong></div><div><span>年間配当</span><strong>${yen(a.dividend)}</strong></div></div><div class="item-actions"><button class="edit-button" data-edit-asset="${a.id}">編集</button><button class="delete-button" data-delete-asset="${a.id}">削除</button></div></article>`}).join(""):`<div class="empty">${currentOwner}の保有資産はまだありません。</div>`}
function renderPlans(){const list=state.plans.filter(p=>p.owner===currentOwner).sort((a,b)=>(b.start||"").localeCompare(a.start||""));$("planList").innerHTML=list.length?list.map(p=>{const months=monthsSince(p.start);return`<article class="item-card"><div class="item-head"><div><div class="item-title">${escapeHtml(p.name)}</div><div class="item-sub">${escapeHtml(p.account)}・開始日 ${escapeHtml(p.start||"未設定")}</div></div><div class="item-value">月 ${yen(p.monthly)}</div></div><div class="item-grid"><div><span>積立月数</span><strong>${months}か月</strong></div><div><span>累計入金額</span><strong>${yen(months*(Number(p.monthly)||0))}</strong></div></div><div class="item-actions"><button class="edit-button" data-edit-plan="${p.id}">編集</button><button class="delete-button" data-delete-plan="${p.id}">削除</button></div></article>`}).join(""):`<div class="empty">${currentOwner}の積立はまだありません。</div>`}
function renderEducation(){$("educationList").innerHTML=state.education.map(e=>{const pct=Math.min(100,e.target?e.current/e.target*100:0);return`<article class="card form-card education-card" data-edu="${e.id}"><h3>${escapeHtml(e.name)}</h3><div class="form-grid"><label>現在額（円）<input class="edu-current" type="number" min="0" value="${Number(e.current)||0}"></label><label>目標額（円）<input class="edu-target" type="number" min="0" value="${Number(e.target)||0}"></label></div><div class="progress"><span style="width:${pct}%"></span></div><p class="section-note">達成率 ${pct.toFixed(1)}%</p><button class="primary save-edu">保存</button></article>`}).join("")}
function renderAll(){renderGreeting();renderTheme();renderHome();renderBudget();renderAssets();renderPlans();renderEducation()}
function clearAsset(){editingAssetId=null;["assetName","assetQuantity","assetCost","assetPrice","assetDividend"].forEach(id=>$(id).value="");$("assetDate").value=today();$("addAssetButton").textContent="保有資産を追加";$("cancelAssetEdit").hidden=true}
function clearPlan(){editingPlanId=null;["planName","planMonthly"].forEach(id=>$(id).value="");$("planStart").value=today();$("addPlanButton").textContent="積立を追加";$("cancelPlanEdit").hidden=true}
function fillAsset(a){editingAssetId=a.id;$("assetName").value=a.name;$("assetType").value=a.type;$("assetAccount").value=a.account;$("assetDate").value=a.date||today();$("assetQuantity").value=a.quantity;$("assetCost").value=a.cost;$("assetPrice").value=a.price;$("assetDividend").value=a.dividend;$("addAssetButton").textContent="変更を保存";$("cancelAssetEdit").hidden=false}
function fillPlan(p){editingPlanId=p.id;$("planName").value=p.name;$("planMonthly").value=p.monthly;$("planStart").value=p.start||today();$("planAccount").value=p.account;$("addPlanButton").textContent="変更を保存";$("cancelPlanEdit").hidden=false}

document.querySelectorAll(".nav-button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".nav-button").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".screen").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(b.dataset.screen).classList.add("active");window.scrollTo(0,0)});
$("themeButton").onclick=()=>{state.dark=!state.dark;save();renderTheme()};
$("saveBasicsButton").onclick=()=>{state.cash=Math.max(0,Number($("cashInput").value)||0);state.loan=Math.max(0,Number($("loanInput").value)||0);save();renderHome();alert("基本情報を保存しました")};
$("budgetMonth").value=currentMonth();$("entryDate").value=today();renderCategory();$("entryType").onchange=renderCategory;$("budgetMonth").onchange=renderBudget;
$("addEntryButton").onclick=()=>{const amount=Number($("entryAmount").value)||0;if(!amount)return alert("金額を入力してください");state.entries.push({id:uid(),type:$("entryType").value,category:$("entryCategory").value,amount,date:$("entryDate").value||today(),memo:$("entryMemo").value.trim()});save();$("entryAmount").value="";$("entryMemo").value="";renderBudget();renderHome()};
$("entryList").onclick=e=>{const id=e.target.dataset.deleteEntry;if(id&&confirm("この記録を削除しますか？")){state.entries=state.entries.filter(x=>x.id!==id);save();renderBudget();renderHome()}};
document.querySelectorAll(".owner-tab").forEach(b=>b.onclick=()=>{currentOwner=b.dataset.owner;document.querySelectorAll(".owner-tab").forEach(x=>x.classList.toggle("active",x===b));clearAsset();clearPlan();renderAssets();renderPlans()});
$("assetSearch").oninput=renderAssets;
$("addAssetButton").onclick=()=>{const name=$("assetName").value.trim();if(!name)return alert("銘柄名を入力してください");const obj={id:editingAssetId||uid(),owner:currentOwner,name,type:$("assetType").value,account:$("assetAccount").value,date:$("assetDate").value||today(),quantity:Number($("assetQuantity").value)||0,cost:Number($("assetCost").value)||0,price:Number($("assetPrice").value)||0,dividend:Number($("assetDividend").value)||0};if(editingAssetId)state.assets=state.assets.map(a=>a.id===editingAssetId?obj:a);else state.assets.push(obj);save();clearAsset();renderAssets();renderHome()};
$("cancelAssetEdit").onclick=clearAsset;$("assetList").onclick=e=>{const edit=e.target.dataset.editAsset,del=e.target.dataset.deleteAsset;if(edit)fillAsset(state.assets.find(a=>a.id===edit));if(del&&confirm("削除しますか？")){state.assets=state.assets.filter(a=>a.id!==del);save();renderAssets();renderHome()}};
$("addPlanButton").onclick=()=>{const name=$("planName").value.trim();if(!name)return alert("商品名を入力してください");const obj={id:editingPlanId||uid(),owner:currentOwner,name,monthly:Number($("planMonthly").value)||0,start:$("planStart").value||today(),account:$("planAccount").value};if(editingPlanId)state.plans=state.plans.map(p=>p.id===editingPlanId?obj:p);else state.plans.push(obj);save();clearPlan();renderPlans();renderHome()};
$("cancelPlanEdit").onclick=clearPlan;$("planList").onclick=e=>{const edit=e.target.dataset.editPlan,del=e.target.dataset.deletePlan;if(edit)fillPlan(state.plans.find(p=>p.id===edit));if(del&&confirm("削除しますか？")){state.plans=state.plans.filter(p=>p.id!==del);save();renderPlans();renderHome()}};
$("educationList").onclick=e=>{if(!e.target.classList.contains("save-edu"))return;const card=e.target.closest(".education-card"),edu=state.education.find(x=>x.id===card.dataset.edu);edu.current=Math.max(0,Number(card.querySelector(".edu-current").value)||0);edu.target=Math.max(0,Number(card.querySelector(".edu-target").value)||0);save();renderEducation();renderHome();alert("教育資金を保存しました")};
$("exportButton").onclick=()=>{const blob=new Blob([JSON.stringify({version:VERSION,exportedAt:new Date().toISOString(),state},null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`sakai-money-pro-backup-${today()}.json`;a.click();URL.revokeObjectURL(a.href)};
$("importInput").onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const data=JSON.parse(await f.text());state={...clone(defaultState),...(data.state||data)};save();renderAll();alert("バックアップを読み込みました")}catch{alert("読み込みに失敗しました")};e.target.value=""};
$("resetButton").onclick=()=>{if(confirm("すべてのデータを初期化しますか？")){state=clone(defaultState);save();renderAll()}};
clearAsset();clearPlan();renderAll();
if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js"));
