"use strict";
const STORAGE_KEY="sakaiMoneyPro7SecondRelease";
const LEGACY_KEYS=["sakaiMoneyPro7FirstRelease","sakaiMoneyPro6FirstRelease","sakaiMoneyPro6SecondRelease"];
const defaultState={cash:0,loan:0,dark:false,assets:[],plans:[],transactions:[],education:{child1:0,child2:0,child3:0,monthly:0}};
let state=loadState();
let currentOwner="本人";
const $=id=>document.getElementById(id);
const yen=value=>new Intl.NumberFormat("ja-JP",{style:"currency",currency:"JPY",maximumFractionDigits:0}).format(Number(value)||0);
const num=value=>Math.max(0,Number(value)||0);
const escapeHtml=value=>String(value??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`;
function clone(v){return JSON.parse(JSON.stringify(v))}
function normalize(raw){const s={...clone(defaultState),...(raw||{})};s.assets=Array.isArray(s.assets)?s.assets:[];s.plans=Array.isArray(s.plans)?s.plans:[];s.transactions=Array.isArray(s.transactions)?s.transactions:[];s.education={...defaultState.education,...(s.education||{})};return s}
function loadState(){try{const own=localStorage.getItem(STORAGE_KEY);if(own)return normalize(JSON.parse(own));for(const key of LEGACY_KEYS){const old=localStorage.getItem(key);if(old){const migrated=normalize(JSON.parse(old));localStorage.setItem(STORAGE_KEY,JSON.stringify(migrated));return migrated}}}catch(e){console.warn(e)}return clone(defaultState)}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function today(){return new Date().toISOString().slice(0,10)}
function monthKey(date=today()){return String(date).slice(0,7)}
function monthsSince(dateString){if(!dateString)return 0;const start=new Date(`${dateString}T00:00:00`),now=new Date();if(start>now)return 0;return (now.getFullYear()-start.getFullYear())*12+(now.getMonth()-start.getMonth())+1}
function assetMetrics(a){const q=num(a.quantity),cost=num(a.cost),price=num(a.price),market=q*price,invested=q*cost,profit=market-invested;return{market,invested,profit,rate:invested?profit/invested*100:0}}
function visibleAssets(){return state.assets.filter(a=>currentOwner==="家族合計"||a.owner===currentOwner)}
function visiblePlans(){return state.plans.filter(p=>currentOwner==="家族合計"||p.owner===currentOwner)}
function investmentTotals(owner=null){const assets=state.assets.filter(a=>!owner||a.owner===owner);const plans=state.plans.filter(p=>!owner||p.owner===owner);const total=assets.reduce((s,a)=>{const m=assetMetrics(a);s.market+=m.market;s.invested+=m.invested;s.profit+=m.profit;s.dividend+=num(a.dividend);return s},{market:0,invested:0,profit:0,dividend:0});for(const p of plans){const months=monthsSince(p.start),contributed=months*num(p.monthly),value=p.value===""||p.value==null?contributed:num(p.value);total.market+=value;total.invested+=contributed;total.profit+=value-contributed}return total}
function budgetTotals(month=monthKey()){return state.transactions.filter(t=>String(t.date).startsWith(month)).reduce((s,t)=>{s[t.kind]+=num(t.amount);return s},{income:0,expense:0})}
function renderGreeting(){const h=new Date().getHours();$("greeting").textContent=`${h<11?"おはよう":h<18?"こんにちは":"こんばんは"}、ヒロ`}
function renderHome(){const inv=investmentTotals(),budget=budgetTotals(),edu=state.education;const financial=num(state.cash)+inv.market+num(edu.child1)+num(edu.child2)+num(edu.child3);$("netWorth").textContent=yen(financial-num(state.loan));$("netWorthSub").textContent=`金融資産 ${yen(financial)} − ローン ${yen(state.loan)}`;$("cashSummary").textContent=yen(state.cash);$("investmentSummary").textContent=yen(inv.market);$("monthlyBalance").textContent=yen(budget.income-budget.expense);$("monthlyBalance").className=budget.income-budget.expense<0?"negative":"positive";$("monthlyPlans").textContent=yen(state.plans.reduce((s,p)=>s+num(p.monthly),0)+num(edu.monthly));$("incomeTotal").textContent=yen(budget.income);$("expenseTotal").textContent=yen(budget.expense);$("dividendTotal").textContent=yen(inv.dividend);$("profitTotal").textContent=yen(inv.profit);$("profitTotal").className=inv.profit<0?"negative":"positive";drawAllocation()}
function drawAllocation(){const inv=investmentTotals().market,edu=num(state.education.child1)+num(state.education.child2)+num(state.education.child3);const parts=[{name:"預金",value:num(state.cash),color:"#9a6f7f"},{name:"投資",value:inv,color:"#c29a6b"},{name:"教育",value:edu,color:"#78958a"}].filter(x=>x.value>0);const canvas=$("allocationChart"),ctx=canvas.getContext("2d"),dpr=window.devicePixelRatio||1,w=canvas.clientWidth||320,h=220;canvas.width=w*dpr;canvas.height=h*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);const total=parts.reduce((s,p)=>s+p.value,0),cx=w/2,cy=95,r=72,inner=42;if(!total){ctx.fillStyle=getComputedStyle(document.body).getPropertyValue("--surface2");ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.fill();ctx.fillStyle=getComputedStyle(document.body).getPropertyValue("--muted");ctx.textAlign="center";ctx.font="13px sans-serif";ctx.fillText("データを入力すると表示されます",cx,cy+5);$("allocationLegend").innerHTML="";return}let start=-Math.PI/2;for(const p of parts){const angle=Math.PI*2*p.value/total;ctx.beginPath();ctx.arc(cx,cy,r,start,start+angle);ctx.arc(cx,cy,inner,start+angle,start,true);ctx.closePath();ctx.fillStyle=p.color;ctx.fill();start+=angle}ctx.fillStyle=getComputedStyle(document.body).getPropertyValue("--text");ctx.textAlign="center";ctx.font="700 14px sans-serif";ctx.fillText("金融資産",cx,cy-2);ctx.font="800 17px sans-serif";ctx.fillText(yen(total),cx,cy+20);$("allocationLegend").innerHTML=parts.map(p=>`<span><i style="background:${p.color}"></i>${p.name} ${Math.round(p.value/total*100)}%</span>`).join("")}
function setupMonthOptions(){const months=new Set(state.transactions.map(t=>monthKey(t.date)));months.add(monthKey());$("txMonth").innerHTML=[...months].sort().reverse().map(m=>`<option value="${m}">${m}</option>`).join("")}
function renderTransactions(){setupMonthOptions();const query=$("txSearch").value.trim().toLowerCase(),month=$("txMonth").value||monthKey();const list=state.transactions.filter(t=>String(t.date).startsWith(month)&&`${t.category} ${t.memo}`.toLowerCase().includes(query)).sort((a,b)=>b.date.localeCompare(a.date));$("txList").innerHTML=list.length?list.map(t=>`<article class="item-card compact"><div><div class="item-title">${escapeHtml(t.category||"未分類")}</div><div class="item-sub">${escapeHtml(t.date)}${t.memo?`・${escapeHtml(t.memo)}`:""}</div></div><div class="tx-right"><strong class="${t.kind==='expense'?'negative':'positive'}">${t.kind==='expense'?'-':'+'}${yen(t.amount)}</strong><button class="delete-button" data-delete-tx="${t.id}">削除</button></div></article>`).join(""):`<div class="empty">この月の記録はありません。</div>`}
function renderOwnerSummary(){const t=currentOwner==="家族合計"?investmentTotals():investmentTotals(currentOwner);$("ownerMarket").textContent=yen(t.market);$("ownerProfit").textContent=yen(t.profit);$("ownerProfit").className=t.profit<0?"negative":"positive";$("ownerDividend").textContent=yen(t.dividend);const editable=currentOwner!=="家族合計";$("assetFormWrap").classList.toggle("hidden",!editable);$("planFormWrap").classList.toggle("hidden",!editable)}
function renderAssets(){const q=$("assetSearch").value.trim().toLowerCase(),filter=$("assetFilter").value;const list=visibleAssets().filter(a=>(filter==="all"||a.type===filter)&&`${a.name} ${a.broker||""}`.toLowerCase().includes(q));$("assetList").innerHTML=list.length?list.map(a=>{const m=assetMetrics(a);return `<article class="item-card"><div class="item-head"><div><div class="item-title">${escapeHtml(a.name)}</div><div class="item-sub">${escapeHtml(a.owner)}・${escapeHtml(a.type)}・${escapeHtml(a.account)}${a.broker?`・${escapeHtml(a.broker)}`:""}</div></div><div class="item-value">${yen(m.market)}<small class="${m.profit<0?'negative':'positive'}">${m.profit>=0?'+':''}${yen(m.profit)}（${m.rate.toFixed(1)}%）</small></div></div><div class="item-grid"><div><span>保有数</span><strong>${num(a.quantity).toLocaleString("ja-JP")}</strong></div><div><span>取得単価</span><strong>${yen(a.cost)}</strong></div><div><span>現在価格</span><strong>${yen(a.price)}</strong></div><div><span>取得総額</span><strong>${yen(m.invested)}</strong></div><div><span>年間配当</span><strong>${yen(a.dividend)}</strong></div><div><span>入力日</span><strong>${escapeHtml(a.date||"—")}</strong></div></div><div class="item-actions"><button class="edit-button" data-edit-asset="${a.id}">編集</button><button class="delete-button" data-delete-asset="${a.id}">削除</button></div></article>`}).join(""):`<div class="empty">保有資産はまだありません。</div>`}
function renderPlans(){const list=visiblePlans();$("planList").innerHTML=list.length?list.map(p=>{const months=monthsSince(p.start),contributed=months*num(p.monthly),value=p.value===""||p.value==null?contributed:num(p.value),profit=value-contributed;return `<article class="item-card"><div class="item-head"><div><div class="item-title">${escapeHtml(p.name)}</div><div class="item-sub">${escapeHtml(p.owner)}・${escapeHtml(p.account)}${p.broker?`・${escapeHtml(p.broker)}`:""}</div></div><div class="item-value">月 ${yen(p.monthly)}<small class="${profit<0?'negative':'positive'}">評価 ${yen(value)}</small></div></div><div class="item-grid"><div><span>開始日</span><strong>${escapeHtml(p.start||"—")}</strong></div><div><span>積立月数</span><strong>${months}か月</strong></div><div><span>累計入金</span><strong>${yen(contributed)}</strong></div><div><span>評価損益</span><strong class="${profit<0?'negative':'positive'}">${profit>=0?'+':''}${yen(profit)}</strong></div></div><div class="item-actions"><button class="edit-button" data-edit-plan="${p.id}">編集</button><button class="delete-button" data-delete-plan="${p.id}">削除</button></div></article>`}).join(""):`<div class="empty">積立はまだありません。</div>`}
function renderDividendCalendar(){const months=Array.from({length:12},(_,i)=>({month:i+1,amount:0,names:[]}));for(const a of visibleAssets()){const dividend=num(a.dividend),ms=String(a.dividendMonths||"").split(/[,、\s]+/).map(Number).filter(m=>m>=1&&m<=12);if(!ms.length)continue;for(const m of ms){months[m-1].amount+=dividend/ms.length;months[m-1].names.push(a.name)}}$("dividendCalendar").innerHTML=months.map(m=>`<div class="month-cell"><span>${m.month}月</span><strong>${yen(m.amount)}</strong><small>${escapeHtml([...new Set(m.names)].join("・"))}</small></div>`).join("")}
function renderEducation(){const e=state.education;$("edu1").value=e.child1||"";$("edu2").value=e.child2||"";$("edu3").value=e.child3||"";$("eduMonthly").value=e.monthly||"";$("edu1Summary").textContent=yen(e.child1);$("edu2Summary").textContent=yen(e.child2);$("edu3Summary").textContent=yen(e.child3);$("eduTotalSummary").textContent=yen(num(e.child1)+num(e.child2)+num(e.child3))}
function renderTheme(){document.body.classList.toggle("dark",state.dark);$("themeButton").textContent=state.dark?"☀️":"🌙"}
function renderAll(){renderGreeting();renderTheme();renderHome();renderTransactions();renderOwnerSummary();renderAssets();renderPlans();renderDividendCalendar();renderEducation();$("cashInput").value=state.cash||"";$("loanInput").value=state.loan||""}
function clearAssetForm(){$("assetId").value="";["assetName","assetBroker","assetQuantity","assetCost","assetPrice","assetDividend","assetDividendMonths"].forEach(id=>$(id).value="");$("assetDate").value=today();$("saveAssetButton").textContent="保有資産を追加";$("cancelAssetEdit").classList.add("hidden")}
function clearPlanForm(){$("planId").value="";["planName","planMonthly","planBroker","planValue"].forEach(id=>$(id).value="");$("planStart").value=today();$("savePlanButton").textContent="積立を追加";$("cancelPlanEdit").classList.add("hidden")}
$("addTxButton").addEventListener("click",()=>{const amount=num($("txAmount").value);if(!amount)return alert("金額を入力してください");state.transactions.push({id:uid(),date:$("txDate").value||today(),kind:$("txKind").value,category:$("txCategory").value.trim()||"未分類",amount,memo:$("txMemo").value.trim()});saveState();["txCategory","txAmount","txMemo"].forEach(id=>$(id).value="");renderAll()});
$("saveAssetButton").addEventListener("click",()=>{const name=$("assetName").value.trim();if(!name)return alert("銘柄・商品名を入力してください");const id=$("assetId").value,data={id:id||uid(),owner:currentOwner,name,type:$("assetType").value,broker:$("assetBroker").value.trim(),account:$("assetAccount").value,date:$("assetDate").value,quantity:num($("assetQuantity").value),cost:num($("assetCost").value),price:num($("assetPrice").value),dividend:num($("assetDividend").value),dividendMonths:$("assetDividendMonths").value.trim()};if(id)state.assets=state.assets.map(a=>a.id===id?data:a);else state.assets.push(data);saveState();clearAssetForm();renderAll()});
$("savePlanButton").addEventListener("click",()=>{const name=$("planName").value.trim();if(!name)return alert("商品名を入力してください");const id=$("planId").value,data={id:id||uid(),owner:currentOwner,name,monthly:num($("planMonthly").value),start:$("planStart").value,broker:$("planBroker").value.trim(),account:$("planAccount").value,value:$("planValue").value===""?null:num($("planValue").value)};if(id)state.plans=state.plans.map(p=>p.id===id?data:p);else state.plans.push(data);saveState();clearPlanForm();renderAll()});
document.addEventListener("click",e=>{const d=e.target.dataset;if(d.deleteAsset&&confirm("この保有資産を削除しますか？")){state.assets=state.assets.filter(a=>a.id!==d.deleteAsset);saveState();renderAll()}if(d.deletePlan&&confirm("この積立を削除しますか？")){state.plans=state.plans.filter(p=>p.id!==d.deletePlan);saveState();renderAll()}if(d.deleteTx&&confirm("この家計記録を削除しますか？")){state.transactions=state.transactions.filter(t=>t.id!==d.deleteTx);saveState();renderAll()}if(d.editAsset){const a=state.assets.find(x=>x.id===d.editAsset);if(a){$("assetId").value=a.id;$("assetName").value=a.name;$("assetType").value=a.type;$("assetBroker").value=a.broker||"";$("assetAccount").value=a.account;$("assetDate").value=a.date||today();$("assetQuantity").value=a.quantity;$("assetCost").value=a.cost;$("assetPrice").value=a.price;$("assetDividend").value=a.dividend;$("assetDividendMonths").value=a.dividendMonths||"";$("saveAssetButton").textContent="変更を保存";$("cancelAssetEdit").classList.remove("hidden");$("assetFormWrap").scrollIntoView({behavior:"smooth"})}}if(d.editPlan){const p=state.plans.find(x=>x.id===d.editPlan);if(p){$("planId").value=p.id;$("planName").value=p.name;$("planMonthly").value=p.monthly;$("planStart").value=p.start||today();$("planBroker").value=p.broker||"";$("planAccount").value=p.account;$("planValue").value=p.value??"";$("savePlanButton").textContent="変更を保存";$("cancelPlanEdit").classList.remove("hidden");$("planFormWrap").scrollIntoView({behavior:"smooth"})}}});
$("cancelAssetEdit").addEventListener("click",clearAssetForm);$("cancelPlanEdit").addEventListener("click",clearPlanForm);
document.querySelectorAll(".owner-tab").forEach(b=>b.addEventListener("click",()=>{currentOwner=b.dataset.owner;document.querySelectorAll(".owner-tab").forEach(x=>x.classList.toggle("active",x===b));clearAssetForm();clearPlanForm();renderOwnerSummary();renderAssets();renderPlans();renderDividendCalendar()}));
document.querySelectorAll(".nav-button").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".screen").forEach(s=>s.classList.toggle("active",s.id===b.dataset.screen));document.querySelectorAll(".nav-button").forEach(x=>x.classList.toggle("active",x===b));window.scrollTo({top:0,behavior:"smooth"});if(b.dataset.screen==="homeScreen")setTimeout(drawAllocation,50)}));
["assetSearch","assetFilter"].forEach(id=>$(id).addEventListener("input",renderAssets));["txSearch","txMonth"].forEach(id=>$(id).addEventListener("input",renderTransactions));
$("saveEducation").addEventListener("click",()=>{state.education={child1:num($("edu1").value),child2:num($("edu2").value),child3:num($("edu3").value),monthly:num($("eduMonthly").value)};saveState();renderAll();alert("教育資金を保存しました")});
$("saveBaseButton").addEventListener("click",()=>{state.cash=num($("cashInput").value);state.loan=num($("loanInput").value);saveState();renderAll();alert("基本情報を保存しました")});
$("themeButton").addEventListener("click",()=>{state.dark=!state.dark;saveState();renderTheme();drawAllocation()});
$("exportButton").addEventListener("click",()=>{const blob=new Blob([JSON.stringify({version:"7.0-second-release",exportedAt:new Date().toISOString(),data:state},null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`sakai-money-pro-backup-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)});
$("importInput").addEventListener("change",async e=>{const file=e.target.files[0];if(!file)return;try{const parsed=JSON.parse(await file.text());state=normalize(parsed.data||parsed);saveState();renderAll();alert("バックアップを読み込みました")}catch{alert("このバックアップは読み込めませんでした")}finally{e.target.value=""}});
$("resetButton").addEventListener("click",()=>{if(!confirm("すべての入力データを削除します。よろしいですか？"))return;state=clone(defaultState);saveState();renderAll()});
$("txDate").value=today();$("assetDate").value=today();$("planStart").value=today();renderAll();
if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(console.error));
